
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Madhu
 */
public class manageStudents extends javax.swing.JFrame {
    
    student std = new student();
    
    DefaultTableModel model;
    public manageStudents() {
        initComponents();
        std.fillStudentJtable(jTable1,"");
        ButtonGroup btngrp= new ButtonGroup();
        btngrp.add(rbtnM);
        btngrp.add(rbtnF);
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.magenta);
        jTable1.setSelectionBackground(Color.black);
                
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public boolean verifText()
    {
        if(txtFN.getText().equals(" ")|| txtLN.getText().equals("")|| txtphn.getText().equals("")||txtadrs.getText().equals("")||txtid1.getText().equals("")||dtpicker1.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "All fields are required");
            return false;
        }
        else if(dtpicker1.getDate().compareTo(new Date())>0)
        {
            JOptionPane.showMessageDialog(null, "invalid Date of Birth!");
            return false;
        }
        else
            return true;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        txtLN = new javax.swing.JTextField();
        rbtnM = new javax.swing.JRadioButton();
        rbtnF = new javax.swing.JRadioButton();
        dtpicker1 = new com.toedter.calendar.JDateChooser();
        txtphn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadrs = new javax.swing.JTextArea();
        btnedit = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnadd1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtsrch = new javax.swing.JTextField();
        txtid1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Students", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 3, 36), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Sex             :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("DoB            :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("phone no. :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Address     :");

        rbtnM.setBackground(new java.awt.Color(51, 0, 51));
        rbtnM.setForeground(new java.awt.Color(204, 204, 204));
        rbtnM.setText("Male");

        rbtnF.setBackground(new java.awt.Color(51, 0, 51));
        rbtnF.setForeground(new java.awt.Color(204, 204, 204));
        rbtnF.setText("Female");

        txtadrs.setColumns(20);
        txtadrs.setRows(5);
        jScrollPane1.setViewportView(txtadrs);

        btnedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_update_172618.png"))); // NOI18N
        btnedit.setText("update");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnremove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnremove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_minus_1645995.png"))); // NOI18N
        btnremove.setText("remove");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Id                :");

        btnadd1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-up-icon-23.png"))); // NOI18N
        btnadd1.setText("Add");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "fist name", "last name", "sex", "DoB", "phone no.", "address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        txtsrch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtsrch.setForeground(new java.awt.Color(204, 204, 204));
        txtsrch.setText("Search here...");
        txtsrch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsrchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsrchFocusLost(evt);
            }
        });
        txtsrch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsrchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtsrchMouseEntered(evt);
            }
        });
        txtsrch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsrchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsrchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsrchKeyTyped(evt);
            }
        });

        txtid1.setEditable(false);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_icon-111-search_314478.png"))); // NOI18N

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Delete_1493279.png"))); // NOI18N
        btncancel.setText("cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btncancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnedit)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dtpicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbtnM)
                                                .addGap(72, 72, 72)
                                                .addComponent(rbtnF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtphn)
                                            .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsrch, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtsrch))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbtnM)
                            .addComponent(rbtnF))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtpicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtphn))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnremove)
                                    .addComponent(btnedit)
                                    .addComponent(btnadd1)
                                    .addComponent(btncancel)))
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(647, 647, 647))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        String fname=txtFN.getText();
        String lname=txtLN.getText();
        String phone =txtphn.getText();
        String address = txtadrs.getText();
        int id = Integer.valueOf(txtid1.getText());
        String sex="" ;
        if(rbtnF.isSelected())
        {
            //rbtnmale.setSelected(false);
            sex = "Female";
        }
        else if(rbtnM.isSelected())
        {
            //rbtnfemale.setSelected(false);
            sex = "Male ";
        }
        if (verifText())
        {
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            String dob =dateformat.format(dtpicker1.getDate());
            student std=new student();
            std.insertUpdateDeleteStudent('u',id, fname, lname, sex, dob, phone, address);
            
            manageStudents.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","fist name","last name","sex","DoB","phone no.","address"}));
           std.fillStudentJtable(manageStudents.jTable1, "");
                txtadrs.setText("");
                txtFN.setText("");
                txtLN.setText("");
                txtphn.setText("");
                dtpicker1.setDate(null);
                rbtnF.setSelected(false);
                rbtnM.setSelected(false);
        }
       

    }//GEN-LAST:event_btneditActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        
        if(txtid1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, " None is selected!");
        }
        int id =Integer.valueOf(txtid1.getText());
        std.insertUpdateDeleteStudent('d',id, null, null, null, null, null, null);
        
       manageStudents.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","fist name","last name","sex","DoB","phone no.","address"}));
        std.fillStudentJtable(manageStudents.jTable1, "");
        
        txtid1.setText("");
        txtadrs.setText("");
        txtFN.setText("");
        txtLN.setText("");
        txtphn.setText("");
        dtpicker1.setDate(null);
        rbtnF.setSelected(false); 
        rbtnM.setSelected(false);
        
        MainForm.lblstd.setText("No of joined Student = "+Integer.toString(myFunction.countData("student")));  
        
        
        
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
       addStudents addstd= new addStudents();
       addstd.setVisible(true);
       addstd.pack();
       addstd.setLocationRelativeTo(null);
       addstd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnadd1ActionPerformed

    int rowIndex;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rowIndex = jTable1.getSelectedRow();
        
        if(model.getValueAt(rowIndex, 3).toString().equals("Male"))
        {
            rbtnM.setSelected(true);
            rbtnF.setSelected(false);
        }
        else{
            rbtnM.setSelected(false);
            rbtnF.setSelected(true);
        }
            
        txtid1.setText(model.getValueAt(rowIndex, 0).toString());
        txtFN.setText(model.getValueAt(rowIndex, 1).toString());
        txtLN.setText(model.getValueAt(rowIndex, 2).toString());
        txtphn.setText(model.getValueAt(rowIndex, 5).toString());
        txtadrs.setText(model.getValueAt(rowIndex, 6).toString());
        Date dob ;
        try {
            dob = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex,4).toString());
            dtpicker1.setDate(dob);
        } catch (ParseException ex) {
            Logger.getLogger(manageStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtsrchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsrchFocusGained
        if(txtsrch.getText().trim().equals("Search here..."))
        {
            txtsrch.setText("");
        }
        txtsrch.setForeground(Color.black);
    }//GEN-LAST:event_txtsrchFocusGained

    private void txtsrchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsrchFocusLost
       if(txtsrch.getText().trim().equals(""))
        {
            txtsrch.setText("Search here...");
        }
        txtsrch.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_txtsrchFocusLost

    private void txtsrchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsrchMouseClicked
        
    }//GEN-LAST:event_txtsrchMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(txtsrch.getText().trim().equals(""))
        {
            txtsrch.setText("Search here...");
        }
        txtsrch.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtsrchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsrchKeyTyped
        if(txtsrch.getText().trim().equals("Search here..."))
        {
            txtsrch.setText("");
        }
        txtsrch.setForeground(Color.black);
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","fist name","last name","sex","DoB","phone no.","address"}));
        std.fillStudentJtable(jTable1, txtsrch.getText());
    }//GEN-LAST:event_txtsrchKeyTyped

    private void txtsrchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsrchKeyPressed
        // TODO add your handling code here:
        if(txtsrch.getText().trim().equals("Search here..."))
        {
            txtsrch.setText("");
        }
        txtsrch.setForeground(Color.black);
        
    }//GEN-LAST:event_txtsrchKeyPressed

    private void txtsrchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsrchKeyReleased
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","fist name","last name","sex","DoB","phone no.","address"}));
        std.fillStudentJtable(jTable1, txtsrch.getText());
        
    }//GEN-LAST:event_txtsrchKeyReleased

    private void txtsrchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsrchMouseEntered
        // TODO add your handling code here:
        //txtsrch.setForeground(Color.black);
    }//GEN-LAST:event_txtsrchMouseEntered

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        
        
        if(evt.getKeyCode() == KeyEvent.VK_UP ||evt.getKeyCode() == KeyEvent.VK_DOWN )
        {
            rowIndex = jTable1.getSelectedRow();
            txtid1.setText(model.getValueAt(rowIndex, 0).toString());
            txtFN.setText(model.getValueAt(rowIndex, 1).toString());
            txtLN.setText(model.getValueAt(rowIndex, 2).toString());
            txtphn.setText(model.getValueAt(rowIndex, 5).toString());
            txtadrs.setText(model.getValueAt(rowIndex, 6).toString());
            
            if(model.getValueAt(rowIndex, 3).toString().equals("Male"))
            {
            rbtnM.setSelected(true);
            rbtnF.setSelected(false);
            }
            else{
            rbtnM.setSelected(false);
            rbtnF.setSelected(true);
            }
            
            Date dob ;
            try {
                dob = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex,4).toString());
                dtpicker1.setDate(dob);
            } catch (ParseException ex) {
                Logger.getLogger(manageStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnremove;
    private com.toedter.calendar.JDateChooser dtpicker1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtnF;
    private javax.swing.JRadioButton rbtnM;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextArea txtadrs;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtphn;
    private javax.swing.JTextField txtsrch;
    // End of variables declaration//GEN-END:variables
}
